# Generated by Django 5.0.3 on 2024-04-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(default='image/None/Noimg.jpg', upload_to='Images/'),
        ),
    ]
